# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aebc792007300efc12d004c9e893ca6efdb0c1d5f2535938f80370ace6a3b8cc4641130d8700348ef54af3f0bbed8d2d3911638dbf634836e890d1ff794bd5f9

test:
  secret_key_base: 09624bff3156c714e2f94bd33b0636023771c9f01f3332326cb15199262943dc61f851f5c9973f4a51e2620667742c2b9ac4eb88cd548309df2cd83ddd19a2f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
